spring:
  application:
    name: mytest
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
server:
  port: 7090

myConfig:
  myObject:
    myName: 张三
    age: 12